../../rtl/RISC_CPU.v
../../rtl/accum.v
../../rtl/addr_mux.v
../../rtl/clk_gen.v
../../rtl/data_control.v
../../rtl/fsm.v
../../rtl/instr_register.v
../../rtl/alu.v
../../rtl/program_counter.v
../../rtl/fsm_ctrl.v
