#!/bin/csh -f

set pathList = (work rpts temp)
#echo "clear file"
foreach name ($pathList)
  if (  -d ./$name) then
    /bin/rm -r  ./$name/*
  else then
    /bin/mkdir ./$name
  endif
end

dc_shell-t -64bit -f synthesis.tcl | tee ./sythesis.log

#echo "SYNTHESIS OVER"
